### ISSUE TITLE
JS > Helpers.js?

### ISSUE THREAD

**Issue by johannpinson** [joscelyn/hetic-p2020-06#10]
A function like this one should be inside a helpers.js 

https://github.com/joscelyn/hetic-p2020-06/blob/7b3547ef3fe798ee4747d229247c5ab76c9b5774/src/js/main.js#L9

**Comment by johannpinson** [comment]
Oh, it a "beautiful" duplicate =>

https://github.com/joscelyn/hetic-p2020-06/blob/dev/src/js/parallaxProduit.js

**Comment by MaudFricht** [comment]
Helpers.js created and duplication erased.
