### ISSUE TITLE
JS > Optimize variable

### ISSUE THREAD

**Issue by johannpinson** [joscelyn/hetic-p2020-06#13]
In this case:
```
let slideActive = document.getElementsByClassName('slide active')[0]
slideActive.classList.remove('active')
let slideActual = event.target.closest('.slide')
slideActual.classList.add('active')
```

You don't need to create the two variables (and they should be a `const`), you can directly change the element after a verification:
```
if (document.querySelector('.slide.active')) {
  document.querySelector('.slide.active').classList.remove('active')
}
if (event.target.closest('.slide') {
  event.target.closest('.slide').classList.add('active')
}
```

And reminder: https://developer.mozilla.org/fr/docs/Web/API/Element/closest#Browser_compatibility

Your code will not work on IE/ME (and it's not work like the jQuery function!)

**Comment by joscelyn** [comment]
Done

**Comment by joscelyn** [comment]
Remplaced closest by matches

**Comment by joscelyn** [comment]
Added polyfill for closest function
