### ISSUE TITLE
NPM > Dependencies management

### ISSUE THREAD

**Issue by johannpinson** [joscelyn/hetic-p2020-06#5]
Don't say to use both npm or yarn for the install, because the files yarn.lock and package-lock.json may not be at the same version.

- [x] Choose package-lock or yarn.lock to manage the depencies (cf. yarnpkg/yarn#3614)

**Comment by johannpinson** [comment]
And so, be careful because you "gitignore" the yarn.lock

**Comment by joscelyn** [comment]
Done
